servo: Merge #4549 - Check for no parameters when invoking cargo (from laumann:master); r=jdm
When invoking `./mach cargo` the following error appeared
```
Error running mach:

    ['cargo']

The error occurred in the implementation of the invoked mach command.

This should never occur and is likely a bug in the implementation of that
command. Consider filing a bug for this issue.

If filing a bug, please include the full output of mach, including this error
message.

The details of the failure are as follows:

TypeError: can only concatenate list (not "NoneType") to list

  File "/home/tj/servo/python/servo/devenv_commands.py", line 24, in cargo
    return subprocess.call(["cargo"] + params,
```
it seems to be that all that's missing is checking whether params is None or not.

Source-Repo: https://github.com/servo/servo
Source-Revision: 3639c4e9818c5421659827b1da1844a9bbb792be