Bug 1287007 - Improve errors for non-existing remote APIs r=billm
Currently, if the remote implementation is missing, the next unhelpful
error message is logged to the console:
"TypeError: findPathInObject(...) is not a function" or
"TypeError: findPathInObject(...) is undefined", etc.

This commit makes the message more useful:
"WebExtension API tabs.create not found (it may be unimplemented by Firefox)"

MozReview-Commit-ID: FhPEYKSjnLm