Bumping gaia.json for 7 gaia-1_3 revision(s) a=gaia-bump
========

https://hg.mozilla.org/integration/gaia-1_3/rev/8af3870d751d
Author: Jim Porter <squibblyflabbetydoo@gmail.com>
Desc: Merge pull request #14793 from jimporter/music-scale-progress

Bug 950783 - [music] Make progress bar scale to the whole width of the screen, no matter the resolution; r=dkuo
(cherry picked from commit 6c7ddcc1bba97fcc2864593a602c0c65aca1ff5c)

========

https://hg.mozilla.org/integration/gaia-1_3/rev/f706bc9e0d28
Author: Andrew Sutherland <asutherland@asutherland.org>
Desc: Merge pull request #15127 from asutherland/163-imap

Bug 951076 - [fugu][buri] Force 163.com to use IMAP with custom autoconfig because the AutoDiscovered ActiveSync implementation deviates from standard. r=mcav
(cherry picked from commit 7e49d834fcc79dd1f75e086ae95f9c5bd78d029c)

========

https://hg.mozilla.org/integration/gaia-1_3/rev/3cd428b96989
Author: Kevin Grandon <kevingrandon@yahoo.com>
Desc: Merge pull request #14998 from KevinGrandon/bug_956012_update_mobile_shims

Bug 956012 - Desktop b2g with local profile is trying to load the SIM / JavaScript error: conn.setVoicePrivacyMode is not a function
(cherry picked from commit fa66acd68ac739690b2b892997de5e43e9fe42e7)

========

https://hg.mozilla.org/integration/gaia-1_3/rev/5c36d4e4d493
Author: Albert <acperez@tid.es>
Desc: Merge pull request #14763 from acperez/bug-937096

Bug 937096 - The ringtone name does not appear in sounds settings.
(cherry picked from commit ee15b42c1efb2b9875465076388a43096e67b813)

========

https://hg.mozilla.org/integration/gaia-1_3/rev/0a4552459388
Author: Jose M. Cantera <jmcanterafonseca@gmail.com>
Desc: Merge pull request #14800 from jmcanterafonseca/fix_active_dup_list

Bug 951562 - Enable active state for the items in the duplicate contacts...
(cherry picked from commit 983d0be9b3517258d537533d2a00456daf073212)

========

https://hg.mozilla.org/integration/gaia-1_3/rev/c83b53f51977
Author: Julien Wajsberg <felash@gmail.com>
Desc: Merge pull request #14415 from julienw/fix-invalid-recipient-width

Bug 946744 - [Messages] Long invalid recipients makes the recipient pane...
(cherry picked from commit 78b443d6b35676dc797c66a692fa2c3f5f9984f1)

========

https://hg.mozilla.org/integration/gaia-1_3/rev/302f758cecda
Author: Arnau <arnau@arnaumarch.com>
Desc: Merge pull request #14404 from rnowm/sticky-headers-SMS

Bug 946693 - Fix sticky headers in [SMS] app
(cherry picked from commit a7d5a5e582b11b14ea7f43b5b6dc2db92a2d9131)