Bug 1765474 - Fix unused-but-set-variable warning in MIDIUtils.cpp. r=gsvelto
dom/midi/MIDIUtils.cpp:110:12: error: variable 'bytesRead' set but not used [-Werror,-Wunused-but-set-variable]
  uint32_t bytesRead = 0;
           ^

Differential Revision: https://phabricator.services.mozilla.com/D144140