Backed out changeset 19db5464f5d1 DONTBUILD r=me a=release
This caused `merge-beta-to-release` to fail on mergeday:

```
ValueError: /app/workdir/src/build/defines.sh does not contain EARLY_BETA_OR_EARLIER=1
```

https://firefox-ci-tc.services.mozilla.com/tasks/auFvwwmrTMika9D9QX37CA/runs/0/logs/https%3A%2F%2Ffirefox-ci-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FauFvwwmrTMika9D9QX37CA%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive_backing.log#L683

EARLY_BETA_OR_EARLIER was correctly unset in https://hg.mozilla.org/releases/mozilla-beta/rev/1ec12ea99d1a0d300224ce331241b9e7a0347aa1