No bug: apply code formatting via Lando
# ignore-this-changeset

Output from `mach lint`:

requesting all changes
adding changesets
adding manifests
adding file changes
added 14948 changesets with 20627 changes to 1598 files
new changesets 90d04a36eef7:41a33c3f2719
updating to branch default
325 files updated, 0 files merged, 0 files removed, 0 files unresolved
0 files updated, 0 files merged, 0 files removed, 0 files unresolved
error: problem with lint setup, skipping android-api-lint, android-checkstyle, android-format, android-javadoc, android-lint, android-test
✖ 0 problems (0 errors, 5 warnings, 1 fixed)