Bug 1766646 - Vendor libwebrtc from b66cfb7414
Upstream commit: https://webrtc.googlesource.com/src/+/b66cfb7414a3790826081049e14fc2ccf2b91b30
    test: Make iOS Test Delegate Class conforms the proper protocol

    Currently, the WebRtcUnitTestDelegate does not conform to the
    GoogleTestRunnerDelegate protocol. So the GoogleTestRunner, designed to
    run googletest based tests using XCTest, fails like this:

    Test Case '-[GoogleTestRunner testRunGoogleTests]' started.
    /../../base/test/ios/google_test_runner.mm:24: error: -[GoogleTestRunner testRunGoogleTests] : (([appDelegate conformsToProtocol:@protocol(GoogleTestRunnerDelegate)]) is true) failed
    Test Case '-[GoogleTestRunner testRunGoogleTests]' failed (0.004 seconds).

    This CL fixes this issue by implementing the GoogleTestRunnerDelegate
    protocol, so googletest based tests run without error.

    No-Presubmit: True
    No-Try: True
    Bug: webrtc:12813
    Change-Id: I6564b41c3aec88a9ddf078104753ceca5e6f0ba6
    Reviewed-on: https://webrtc-review.googlesource.com/c/src/+/220260
    Reviewed-by: Mirko Bonadei <mbonadei@webrtc.org>
    Reviewed-by: Artem Titov <titovartem@webrtc.org>
    Commit-Queue: Mirko Bonadei <mbonadei@webrtc.org>
    Cr-Commit-Position: refs/heads/master@{#34593}