servo: Merge #6831 - Document libglu1-mesa-dev dependency (from Ms2ger:glu); r=larsbergstrom
Missing this caused
  src/gpu/gl/unix/SkNativeGLContext_unix.cpp:10:20:
  fatal error: GL/glu.h: No such file or directory
on my new laptop.

Source-Repo: https://github.com/servo/servo
Source-Revision: cc98026487514889ace9d7fbacd1542fc963a1aa