Bug 1933625 - Fix verifyRunBlockingAndStrictModeSuppresionCount perf test r=petru
The UI test started to fail again after [[ https://bugzilla.mozilla.org/show_bug.cgi?id=1934680 | this ]] change landed.

The test was failing because the number of times StrictMode violations were suppressed during the test run did not match the expected number of suppressions:


```
java.lang.AssertionError: StrictMode suppression count does not match expected count.

    This heuristic-based performance test is expected measure the number of occurrences of known
    performance anti-patterns and fail when that count changes. Please read the class documentation
    for more details about this test and an explanation of what the failed heuristic is expected to
    measure. Please consult the performance team if you have questions.

 expected:<18> but was:<19>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.mozilla.fenix.perf.StartupExcessiveResourceUseTest.verifyRunBlockingAndStrictModeSuppresionCount(StartupExcessiveResourceUseTest.kt:117)
```

Based on the error I've incremented the EXPECTED_SUPPRESSION_COUNT variable again.

The UI test successfully passed 10x on Firebase ✅
All UI tests successfully passed 1x on Firebase ✅

Differential Revision: https://phabricator.services.mozilla.com/D231063