Bug 1904400 [wpt PR 46881] - [wptrunner] Don't honor per-request timeout for now, a=testonly
Automatic update from web-platform-tests
[wptrunner] Don't honor per-request timeout for now (#46881)

This is a partial revert of #46869. Using a nondefault timeout fails
with:

```
  ▶ ERROR [expected OK] external/wpt/IndexedDB/idbindex-query-exception-order.html
  └   → WebDriverRun.run_func didn't set a result

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/tmp/wpt/tools/webdriver/webdriver/transport.py", line 259, in _request
    previous_timeout = self._conn.gettimeout()
AttributeError: 'HTTPConnection' object has no attribute 'gettimeout'
```

... because `{get,set}timeout` are methods on `socket.socket`, not
`http.client.HTTP(S)Connection`.
--

wpt-commits: c5ca5a50f676f0c609a79f86fb85c8ccc95952ab
wpt-pr: 46881